name: Deploy to cPanel
on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: voiture.o2switch.net
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        protocol: ftp
        server-dir: /public_html/
